apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oblingress
  labels:
    name: oblingress
spec:
  rules:
  - host: *.amazonaws.com
    http:
      paths:
      - pathType: Prefix
        path: "/ms-product"
        backend:
          service:
            name: ms-product-svc
            port: 
              number: 8080
